"""Add password to user and basic logins

Revision ID: 2755e965508f
Revises: ab336518d0ed
Create Date: 2025-10-12 22:40:50.564167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2755e965508f'
down_revision: Union[str, None] = 'ab336518d0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drivers', 'team_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.alter_column('drivers', 'team_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
