"""Add check for 2 drivers

Revision ID: ab336518d0ed
Revises: 389178733482
Create Date: 2025-10-12 21:57:00.748794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab336518d0ed'
down_revision: Union[str, None] = '389178733482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grand_prix', sa.Column('total_distance', sa.Integer(), nullable=False))
    op.add_column('grand_prix', sa.Column('total_laps', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grand_prix', 'total_laps')
    op.drop_column('grand_prix', 'total_distance')
    # ### end Alembic commands ###
