"""add initial f1 data

Revision ID: c0439aad54c7
Revises: 99057244b7d2
Create Date: 2025-11-16 23:57:33.729875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import bcrypt


# revision identifiers, used by Alembic.
revision: str = 'c0439aad54c7'
down_revision: Union[str, None] = '99057244b7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'strategies', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'strategies', 'grand_prix', ['grand_prix_id'], ['id'])
    op.create_foreign_key(None, 'strategies', 'drivers', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'strategies', 'teams', ['team_id'], ['id'])

    conn = op.get_bind()
    
    # Insert Grand Prix events (2024 season)
    conn.execute(sa.text("""
        INSERT INTO grand_prix (name, year) VALUES
        ('Bahrain Grand Prix', 2024),
        ('Saudi Arabian Grand Prix', 2024),
        ('Australian Grand Prix', 2024),
        ('Japanese Grand Prix', 2024),
        ('Chinese Grand Prix', 2024),
        ('Miami Grand Prix', 2024),
        ('Monaco Grand Prix', 2024),
        ('Canadian Grand Prix', 2024),
        ('Spanish Grand Prix', 2024),
        ('Austrian Grand Prix', 2024),
        ('British Grand Prix', 2024),
        ('Hungarian Grand Prix', 2024),
        ('Belgian Grand Prix', 2024),
        ('Dutch Grand Prix', 2024),
        ('Italian Grand Prix', 2024),
        ('Singapore Grand Prix', 2024),
        ('United States Grand Prix', 2024),
        ('Mexico City Grand Prix', 2024),
        ('Brazilian Grand Prix', 2024),
        ('Las Vegas Grand Prix', 2024),
        ('Abu Dhabi Grand Prix', 2024)
    """))
    
    # Insert Teams
    conn.execute(sa.text("""
        INSERT INTO teams (name) VALUES
        ('Red Bull Racing'),
        ('Ferrari'),
        ('Mercedes'),
        ('McLaren'),
        ('Aston Martin'),
        ('Alpine'),
        ('Williams'),
        ('RB'),
        ('Kick Sauber'),
        ('Haas')
    """))
    
    # Insert Drivers
    conn.execute(sa.text("""
        INSERT INTO drivers (name, surname, team_id) VALUES
        ('Max', 'Verstappen', 1),
        ('Sergio', 'Pérez', 1),
        ('Charles', 'Leclerc', 2),
        ('Carlos', 'Sainz', 2),
        ('Lewis', 'Hamilton', 3),
        ('George', 'Russell', 3),
        ('Lando', 'Norris', 4),
        ('Oscar', 'Piastri', 4),
        ('Fernando', 'Alonso', 5),
        ('Lance', 'Stroll', 5),
        ('Pierre', 'Gasly', 6),
        ('Esteban', 'Ocon', 6),
        ('Alex', 'Albon', 7),
        ('Logan', 'Sargeant', 7),
        ('Daniel', 'Ricciardo', 8),
        ('Yuki', 'Tsunoda', 8),
        ('Valtteri', 'Bottas', 9),
        ('Zhou', 'Guanyu', 9),
        ('Kevin', 'Magnussen', 10),
        ('Nico', 'Hülkenberg', 10)
    """))
    
    # Create demo users
    hashed_password_admin = bcrypt.hashpw('Admin123'.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
    conn.execute(sa.text("""
        INSERT INTO users (username, email, hashed_password, role) VALUES
        ('admin', 'admin@f1strategies.com', :password, 'admin')
    """), {'password': hashed_password_admin})
    
    hashed_password_user = bcrypt.hashpw('F1fan123'.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
    conn.execute(sa.text("""
        INSERT INTO users (username, email, hashed_password, role) VALUES
        ('f1fan', 'fan@f1strategies.com', :password, 'user')
    """), {'password': hashed_password_user})
    
    # Insert sample strategies
    conn.execute(sa.text("""
        INSERT INTO strategies (name, description, parameters, approved, grand_prix_id, driver_id, user_id, team_id) VALUES
        (
            'Monaco Aggressive One-Stop',
            'High-risk one-stop strategy for Monaco with late tire change',
            '{"pit_stops": [{"lap": 45, "tire": "Hard", "fuel": "Medium"}], "tire_strategy": "Soft->Hard", "fuel_mode": "Aggressive"}',
            true,
            7,
            1,
            1,
            1
        ),
        (
            'Monza Slipstream Master',
            'Two-stop strategy optimized for slipstreaming on Monza straights',
            '{"pit_stops": [{"lap": 20, "tire": "Medium", "fuel": "High"}, {"lap": 40, "tire": "Soft", "fuel": "Low"}], "tire_strategy": "Soft->Medium->Soft", "fuel_mode": "Balanced"}',
            true,
            15,
            3,
            2,
            2
        ),
        (
            'Silverstone Rain Gamble',
            'Adaptive strategy for unpredictable British weather',
            '{"pit_stops": [{"lap": 15, "tire": "Intermediate", "fuel": "Medium"}, {"lap": 35, "tire": "Soft", "fuel": "Low"}], "tire_strategy": "Wet->Inter->Soft", "fuel_mode": "Conservative"}',
            true,
            11,
            5,
            2,
            3
        ),
        (
            'Spa Long Stint Strategy',
            'Conservative two-stop for Spa-Francorchamps',
            '{"pit_stops": [{"lap": 18, "tire": "Medium", "fuel": "High"}, {"lap": 38, "tire": "Medium", "fuel": "Medium"}], "tire_strategy": "Medium->Medium->Medium", "fuel_mode": "Balanced"}',
            true,
            13,
            7,
            2,
            4
        ),
        (
            'Singapore Night Race Special',
            'Three-stop aggressive strategy for Singapore street circuit',
            '{"pit_stops": [{"lap": 15, "tire": "Soft", "fuel": "Low"}, {"lap": 30, "tire": "Soft", "fuel": "Low"}, {"lap": 45, "tire": "Soft", "fuel": "Low"}], "tire_strategy": "Soft->Soft->Soft->Soft", "fuel_mode": "Aggressive"}',
            false,
            16,
            9,
            2,
            5
        ),
        (
            'Abu Dhabi Undercut Master',
            'Undercut-focused strategy for season finale',
            '{"pit_stops": [{"lap": 18, "tire": "Hard", "fuel": "Medium"}, {"lap": 42, "tire": "Medium", "fuel": "Low"}], "tire_strategy": "Soft->Hard->Medium", "fuel_mode": "Balanced"}',
            false,
            21,
            11,
            2,
            6
        )
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.drop_column('strategies', 'team_id')

    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM strategies"))
    conn.execute(sa.text("DELETE FROM drivers"))
    conn.execute(sa.text("DELETE FROM teams"))
    conn.execute(sa.text("DELETE FROM grand_prix"))
    conn.execute(sa.text("DELETE FROM users WHERE username IN ('admin', 'f1fan')"))
    # ### end Alembic commands ###
