"""edit table driver

Revision ID: f5a1a71e42f5
Revises: c0439aad54c7
Create Date: 2025-11-17 00:04:16.295394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f5a1a71e42f5'
down_revision: Union[str, None] = 'c0439aad54c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drivers', 'team_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'drivers', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.alter_column('drivers', 'team_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
